### PR TITLE
opendbx support

### LINKED ISSUE #8: OpenDKIM Database support
DKIM optionally supports databases via opendbx.

Would be willing to contribute SQL support if it would be merged.

<details>
  <summary>My current Dockerfile for DKIM</summary>

```Dockerfile
FROM alpine:3.14

ENV DKIM_SOCKET="inet:3000"

EXPOSE 3000

# Install dependencies
RUN apk add --no-cache \
    gettext \
    libmilter \
    mariadb-dev \
    s6-overlay \
  && apk add --no-cache --virtual .tool-deps \
    coreutils autoconf automake g++ libtool make \
     \
  && apk add --no-cache --virtual .build-deps \
    db-dev \
    libmilter-dev \
    openssl-dev \
    readline-dev

# Copy pre-downloaded packages
COPY packages /opt/packages/

# Compile and install opendbx
RUN cd /opt/packages \
  && tar xzf opendbx-1.4.6.tar.gz \
  && cp config.guess opendbx-1.4.6 \
  && cp config.sub opendbx-1.4.6 \
  && cd opendbx-1.4.6/ \
  && CPPFLAGS="-I/usr/include/mysql" ./configure --with-backends="mysql" \
  && make install

# Compile and install OpenDKIM
# The apk version doesn't have important flags we need
RUN cd /opt/packages \
  && tar xzf 2.11.0-Beta2.tar.gz \
  && cd OpenDKIM-2.11.0-Beta2 \
  && autoreconf -vif \
  && CPPFLAGS="-I/usr/include/openssl" ./configure \
    --sysconfdir=/etc/opendkim \
    --with-odbx \
    --with-openssl \
    --with-sql-backend \
    --docdir=/tmp/opendkim/doc \
    --htmldir=/tmp/opendkim/html \
    --infodir=/tmp/opendkim/info \
    --mandir=/tmp/opendkim/man \
  && make \
  && addgroup -S -g 91 opendkim \
  && adduser \
    -S -u 90 -D \
    -s /sbin/nologin \
    -H -h /run/opendkim \
    -G opendkim -g opendkim \
    opendkim \
  && addgroup opendkim mail \
  && make install \
  && install -d -o opendkim -g opendkim /run/opendkim/ \
  && install -d /etc/opendkim/conf.d/ \
  && install -d /usr/share/licenses/opendkim/ \
  && mv /tmp/opendkim/doc/LICENSE* /usr/share/licenses/opendkim/ \
    \
  && apk del .tool-deps .build-deps \
  && rm -rf /var/cache/apk/* /tmp/*

RUN mkdir -p /etc/opendkim/

# Copy files
COPY rootfs /

ENTRYPOINT ["/init"]

CMD ["opendkim", "-f"]
```
</details>

### PR DESCRIPTION
**Pull request by jchook**
Closes #8

Adds opendbx support for mysql and postgres.

The uncompressed image size difference seems small, all things considered.

| OS     | Previous | Updated | Difference |
|--------|----------|---------|------------|
| Debian | 97.1M    | 98.7M   | +2.7%      |
| Alpine | 57.5M    | 59.4M   | +3.2%      |

### CODE REVIEW

**Comment by jchook** [comment]
@tyranron This is ready to be merged IMO.

Unfortunately testing the db required a full end-to-end test, but I wrote one and it passes.

Happy to make any adjustments per your feedback.

**Review by tyranron — CHANGES_REQUESTED** [review]
@jchook thanks for the amazing effort and work! ♥️

I've tuned a bit the `Dockerfile` to my preferring.

The only thing that concerns me (in terms of understanding and maintance), is that monstrous E2E test:
1. It seems that using [`teardown` function](https://bats-core.readthedocs.io/en/stable/tutorial.html#cleaning-up-your-mess) rather than a separate test for cleaning "mess" would be better. [`setup` function](https://bats-core.readthedocs.io/en/stable/tutorial.html#let-s-do-some-setup) also would be helpful here to decompose the test clearly.
2. Could we use the `docker-compose.yml` to setup the test environment rather than juggling with containers and IPs via raw `docker` commands?

**Comment by jchook** [comment]
> @jchook thanks for the amazing effort and work! hearts

Thank you for maintaining this excellent OpenDKIM docker!

> I've tuned a bit the `Dockerfile` to my preferring.

Great work. Much cleaner now.

> The only thing that concerns me (in terms of understanding and maintance), is that monstrous E2E test:

Unfortunately I think e2e is the only way to properly test this :(

> 1. It seems that using [`teardown` function](https://bats-core.readthedocs.io/en/stable/tutorial.html#cleaning-up-your-mess) rather than a separate test for cleaning "mess" would be better. [`setup` function](https://bats-core.readthedocs.io/en/stable/tutorial.html#let-s-do-some-setup) also would be helpful here to decompose the test clearly.

Yep makes sense. I was just unfamiliar with bats.

> 2. Could we use the `docker-compose.yml` to setup the test environment rather than juggling with containers and IPs via raw `docker` commands?

It's certainly feasible.

Unfortunately the static IP assignment seems necessary to me because Docker's DNS feature does not provide a way to publish arbitrary TXT records (which is necessary for DKIM to function end-to-end). As a result, the DNS host is needed and, baring some fancy entrypoint nsupdate sorcery, known IPs reduce the moving parts.

I originally planned to use a docker-compose.yml approach, but opted for this instead.

To me it seems easier to maintain the sequential execution rather than letting docker compose try to start everything all at once and having to manage separate entrypoint scripts to wait for the database to provision, compose overrides for each db, etc. I also saw other tests used this method.

I'll await the failing test fixes, then update the bats test to use setup/teardown. Let me know your thoughts on docker compose.

**Comment by jchook** [comment]
A couple more thoughts:

- The presence of a full E2E test enhances my confidence. I think it makes the project more robust and trustworthy. It also provides some usage examples.

-  OpenDKIM is essentially unmaintained/dead software (died on a Beta no less). Our key threats for maintenance are docker and docker-compose API changes. It seems plausible that this E2E test will not require maintenance during it's remaining lifetime.

**Comment by tyranron** [comment]
@jchook 

> To me it seems easier to maintain the sequential execution rather than letting docker compose try to start everything all at once and having to manage separate entrypoint scripts to wait for the database to provision, compose overrides for each db, etc. I also saw other tests used this method.

This is solvable with Docker Compose. Just use manifest version `"2.4"` and `healthcheck` + `depends_on: <service>: condition: service_healthy`. This way you can make them start in the desired sequence.

However, regarding the static IP assignment in Docker Compose, I'm not sure if it's possible. Here you should look into docs. Usually, Docker Compose allows everything which raw Docker does.

**Comment by jchook** [comment]
I'm going to close this PR.

Feel free to rewrite the tests to your liking.

BTW you can also reduce your image size by ~50% if you combine the RUN statements together.

**Pull request closed without merging**
